const styles = {
    container: {
      width: '400px',
      margin: '50px auto',
      textAlign: 'center',
      position: 'relative',
    },
    fieldset: {
      background: 'white',
      border: 'none',
      borderRadius: '3px',
      boxShadow: '0 0 15px 1px rgba(0, 0, 0, 0.4)',
      padding: '20px 30px',
      boxSizing: 'border-box',
      width: '80%',
      margin: '0 10%',
      position: 'relative',
    },
    input: {
      padding: '15px',
      border: '1px solid #ccc',
      borderRadius: '3px',
      marginBottom: '10px',
      width: '100%',
      boxSizing: 'border-box',
      fontFamily: 'montserrat',
      color: '#2C3E50',
      fontSize: '13px',
    },
    button: {
      width: '100px',
      background: '#27AE60',
      fontWeight: 'bold',
      color: 'white',
      border: 'none',
      borderRadius: '1px',
      cursor: 'pointer',
      padding: '10px',
      margin: '10px 5px',
      textDecoration: 'none',
      fontSize: '14px',
    },
    progressbar: {
      marginBottom: '30px',
      overflow: 'hidden',
      counterReset: 'step',
    },
    progressbarItem: {
      listStyleType: 'none',
      color: 'white',
      textTransform: 'uppercase',
      fontSize: '9px',
      width: '33.33%',
      float: 'left',
      position: 'relative',
    },
    progressbarItemBefore: {
      content: 'counter(step)',
      counterIncrement: 'step',
      width: '20px',
      lineHeight: '20px',
      display: 'block',
      fontSize: '10px',
      color: '#333',
      background: 'white',
      borderRadius: '3px',
      margin: '0 auto 5px auto',
    },
    progressbarItemAfter: {
      content: '',
      width: '100%',
      height: '2px',
      background: 'white',
      position: 'absolute',
      left: '-50%',
      top: '9px',
      zIndex: '-1',
    },
    progressbarItemFirstAfter: {
      content: 'none',
    },
    progressbarItemActiveBefore: {
      background: '#27AE60',
      color: 'white',
    },
    fsTitle: {
      fontSize: '15px',
      textTransform: 'uppercase',
      color: '#2C3E50',
      marginBottom: '10px',
    },
    fsSubtitle: {
      fontWeight: 'normal',
      fontSize: '13px',
      color: '#666',
      marginBottom: '20px',
    },
  };
  
  export default styles;
  